sudo: required
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install .[viz] --process-dependency-links
  - pip install pyflakes
  - sudo apt-get update
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y imagemagick
script:
  - pyflakes adage
  - python examples/simple.py
