language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install . --process-dependency-links
  - pip install pyflakes
  - apt-get install -y graphviz
  - apt-get install -y imagemagick
script:
  - pyflakes adage
  - python examples/simple.py
