language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install . --process-dependency-links
  - pip install pyflakes
script:
  - pyflakes adage
  - python examples/simple.py
